// Generated by `baseplate types`. Regenerate after a schema change.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type BoardsRow = {
  id: string;
  owner_id: string;
  title: string;
  created_at: string;
};

export type BoardsInsert = {
  title: string;
  created_at?: string;
};

export type BoardsUpdate = {
  title?: string;
  created_at?: string;
};

export type CardsRow = {
  id: string;
  owner_id: string;
  list_id: string;
  title: string;
  position: number;
};

export type CardsInsert = {
  list_id: string;
  title: string;
  position: number;
};

export type CardsUpdate = {
  list_id?: string;
  title?: string;
  position?: number;
};

export type ListsRow = {
  id: string;
  owner_id: string;
  board_id: string;
  title: string;
  position: number;
};

export type ListsInsert = {
  board_id: string;
  title: string;
  position: number;
};

export type ListsUpdate = {
  board_id?: string;
  title?: string;
  position?: number;
};

export type Database = {
  boards: {
    Row: BoardsRow;
    Insert: BoardsInsert;
    Update: BoardsUpdate;
  };
  cards: {
    Row: CardsRow;
    Insert: CardsInsert;
    Update: CardsUpdate;
  };
  lists: {
    Row: ListsRow;
    Insert: ListsInsert;
    Update: ListsUpdate;
  };
};
