import type { Column, SchemaChange } from "#domain";

const BREAKPOINT = "--> statement-breakpoint";

/**
 * Renders a schema change as Postgres DDL in drizzle-kit's file format, so a
 * migration written here and one generated by drizzle-kit are the same shape.
 * Identifiers are already constrained by the domain, so quoting is enough.
 */
export function renderChange(change: SchemaChange): string {
  if (change.kind === "create-table") {
    const lines = [
      `\t"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL`,
      `\t"${change.ownerColumn}" uuid NOT NULL`,
      ...change.columns.map((column) => `\t${columnClause(column)}`),
    ];
    return `CREATE TABLE "${change.table}" (\n${lines.join(",\n")}\n);`;
  }
  if (change.kind === "drop-table") {
    return `DROP TABLE "${change.table}";`;
  }
  if (change.kind === "rename-table") {
    return `ALTER TABLE "${change.table}" RENAME TO "${change.to}";`;
  }
  if (change.kind === "add-column") {
    return `ALTER TABLE "${change.table}" ADD COLUMN ${columnClause(change.column)};`;
  }
  return `ALTER TABLE "${change.table}" DROP COLUMN "${change.column}";`;
}

export function joinStatements(statements: readonly string[]): string {
  return statements.join(`\n${BREAKPOINT}\n`);
}

function columnClause(column: Column): string {
  const nullable = column.nullable ? "" : " NOT NULL";
  return `"${column.name}" ${column.type}${nullable}`;
}
