import { randomBytes } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { DomainError } from "#domain";
import { parseEnvMap, upsertEnv, writeSecretFile } from "./env-file.ts";
import { CONFIG_FILE } from "../paths.ts";

/** What `baseplate init` writes. Every secret in it is generated per project. */
export const TEMPLATE = `# Baseplate project config. Generated by \`baseplate init\`.
# Everything here stays on this machine. Your cloud credentials never leave it.

TARGET=local
BASEPLATE_HOSTNAME=localhost

HTTP_PORT=8080
SITE_ADDRESS=:8080
# Loopback only. The operator tool applies schema changes over this.
POSTGRES_PORT=5432
# Where the studio is served, on 127.0.0.1 only.
DASHBOARD_PORT=8788

# Which origins a browser app may call this API from. * suits local work;
# name your app's origin once it has one.
CORS_ORIGIN=*

# The largest file an app may upload, in bytes. 25 MB by default.
STORAGE_MAX_BYTES=26214400
# Where object bytes are kept. The bundled store runs beside the stack and is
# never published; point these at Hetzner Object Storage, B2, or S3 to use one.
STORAGE_ENDPOINT=http://storage-blobs:8333
STORAGE_BUCKET=baseplate
STORAGE_REGION=us-east-1

# How long a signed-in user's tokens last. 900, 15m, 12h, and 30d all parse.
ACCESS_TOKEN_TTL=1h
REFRESH_TOKEN_TTL=30d

# Where your app is served. Password reset and email confirmation links point
# here, so it has to be an address the person clicking one can actually reach.
SITE_URL=http://localhost:3000
# Mail. Leave SMTP_HOST blank and mail goes to the Mailpit inbox that runs
# beside the stack locally, so a reset link is readable without a mail account.
# Fill these in from your provider before anyone outside your machine signs up.
SMTP_HOST=
SMTP_PORT=
SMTP_USER=
SMTP_PASS=
SMTP_FROM=
# none, starttls, or tls. Providers usually want starttls on 587, tls on 465.
SMTP_SECURE=none
# Where to read the local inbox, on 127.0.0.1 only.
MAILPIT_UI_PORT=8025
# Whether a new account has to click the link before it can sign in. Off, so
# your first app works the minute it is written; turn it on before real users.
REQUIRE_EMAIL_CONFIRM=false

# Backups. BACKUP_KEY seals them and is the only thing that opens them again:
# lose it and the backups are noise. It is generated for this project and it
# does go to the server, because the restore drill has to run where the
# database is.
BACKUP_EVERY=24h
DRILL_EVERY=168h
BACKUP_KEEP=14
# Where sealed backups go. Leave these blank and they stay on the same machine
# as the database, which is better than nothing and is not a backup. Any
# S3-compatible bucket works: Hetzner Object Storage, Backblaze B2, S3.
BACKUP_S3_ENDPOINT=
BACKUP_S3_BUCKET=
BACKUP_S3_REGION=us-east-1
BACKUP_S3_ACCESS_KEY=
BACKUP_S3_SECRET_KEY=

# Hetzner is bring-your-own-key. These are YOUR account credentials.
# Baseplate has no cloud account. Fill them in from Settings when you are ready.
HCLOUD_TOKEN=
HETZNER_DNS_ZONE=
SSH_KEY_NAME=
SERVER_LOCATION=nbg1
`;

export function secretValue(): string {
  return randomBytes(32).toString("base64url");
}

export function writeLocalFirstRun(root: string): void {
  const envPath = resolve(root, CONFIG_FILE);
  const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : TEMPLATE;
  const current = parseEnvMap(existing);
  const jwt = current.JWT_SECRET && current.JWT_SECRET.length >= 32
    ? current.JWT_SECRET
    : secretValue();
  const next = upsertEnv(existing, {
    TARGET: "local",
    JWT_SECRET: jwt,
    POSTGRES_PASSWORD: current.POSTGRES_PASSWORD || secretValue(),
    AUTHENTICATOR_PASSWORD: current.AUTHENTICATOR_PASSWORD || secretValue(),
    AUTH_SERVICE_PASSWORD: current.AUTH_SERVICE_PASSWORD || secretValue(),
    STORAGE_SERVICE_PASSWORD: current.STORAGE_SERVICE_PASSWORD || secretValue(),
    STORAGE_ACCESS_KEY: current.STORAGE_ACCESS_KEY || secretValue(),
    STORAGE_SECRET_KEY: current.STORAGE_SECRET_KEY || secretValue(),
    BACKUP_KEY: current.BACKUP_KEY || secretValue(),
    HTTP_PORT: current.HTTP_PORT || "8080",
    POSTGRES_PORT: current.POSTGRES_PORT || "5432",
    DASHBOARD_PORT: current.DASHBOARD_PORT || "8788",
    BASEPLATE_HOSTNAME: current.BASEPLATE_HOSTNAME || "localhost",
    SITE_ADDRESS: current.SITE_ADDRESS || ":8080",
  });
  writeSecretFile(envPath, next);
}

export function ensureOperatorSecrets(root: string): void {
  const envPath = resolve(root, CONFIG_FILE);
  if (!existsSync(envPath)) {
    return;
  }
  const existing = readFileSync(envPath, "utf8");
  const current = parseEnvMap(existing);
  const updates: Record<string, string> = {};
  for (const key of [
    "AUTH_SERVICE_PASSWORD",
    "STORAGE_SERVICE_PASSWORD",
    "STORAGE_ACCESS_KEY",
    "STORAGE_SECRET_KEY",
    "BACKUP_KEY",
  ]) {
    if (!current[key]) {
      updates[key] = secretValue();
    }
  }
  if (Object.keys(updates).length === 0) {
    return;
  }
  writeSecretFile(envPath, upsertEnv(existing, updates));
}

export function writeOperatorEnv(
  root: string,
  updates: Record<string, string>,
): void {
  const envPath = resolve(root, CONFIG_FILE);
  if (!existsSync(envPath)) {
    throw new DomainError(
      "cli.missing_env_file",
      "Run local first-run before saving Hetzner keys.",
    );
  }
  const next = upsertEnv(readFileSync(envPath, "utf8"), updates);
  writeSecretFile(envPath, next);
}
