import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { DomainError } from "#domain";
import { parseEnvMap, upsertEnv } from "./env-file.ts";
import { CONFIG_FILE } from "../paths.ts";

/** What `baseplate init` writes. Every secret in it is generated per project. */
export const TEMPLATE = `# Baseplate project config. Generated by \`baseplate init\`.
# Everything here stays on this machine. Your cloud credentials never leave it.

TARGET=local
BASEPLATE_HOSTNAME=localhost

HTTP_PORT=8080
SITE_ADDRESS=:8080
# Loopback only. The operator tool applies schema changes over this.
POSTGRES_PORT=5432
# Where the studio is served, on 127.0.0.1 only.
DASHBOARD_PORT=8788

# Which origins a browser app may call this API from. * suits local work;
# name your app's origin once it has one.
CORS_ORIGIN=*

# How long a signed-in user's tokens last. 900, 15m, 12h, and 30d all parse.
ACCESS_TOKEN_TTL=1h
REFRESH_TOKEN_TTL=30d

# Hetzner is bring-your-own-key. These are YOUR account credentials.
# Baseplate has no cloud account. Fill them in from Settings when you are ready.
HCLOUD_TOKEN=
HETZNER_DNS_TOKEN=
HETZNER_DNS_ZONE=
SSH_KEY_NAME=
SERVER_LOCATION=nbg1
`;

export function secretValue(): string {
  return randomBytes(32).toString("base64url");
}

export function writeLocalFirstRun(root: string): void {
  const envPath = resolve(root, CONFIG_FILE);
  const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : TEMPLATE;
  const current = parseEnvMap(existing);
  const jwt = current.JWT_SECRET && current.JWT_SECRET.length >= 32
    ? current.JWT_SECRET
    : secretValue();
  const next = upsertEnv(existing, {
    TARGET: "local",
    JWT_SECRET: jwt,
    POSTGRES_PASSWORD: current.POSTGRES_PASSWORD || secretValue(),
    AUTHENTICATOR_PASSWORD: current.AUTHENTICATOR_PASSWORD || secretValue(),
    AUTH_SERVICE_PASSWORD: current.AUTH_SERVICE_PASSWORD || secretValue(),
    HTTP_PORT: current.HTTP_PORT || "8080",
    POSTGRES_PORT: current.POSTGRES_PORT || "5432",
    DASHBOARD_PORT: current.DASHBOARD_PORT || "8788",
    BASEPLATE_HOSTNAME: current.BASEPLATE_HOSTNAME || "localhost",
    SITE_ADDRESS: current.SITE_ADDRESS || ":8080",
  });
  writeFileSync(envPath, next, "utf8");
}

export function ensureOperatorSecrets(root: string): void {
  const envPath = resolve(root, CONFIG_FILE);
  if (!existsSync(envPath)) {
    return;
  }
  const existing = readFileSync(envPath, "utf8");
  const current = parseEnvMap(existing);
  const updates: Record<string, string> = {};
  if (!current.AUTH_SERVICE_PASSWORD) {
    updates.AUTH_SERVICE_PASSWORD = secretValue();
  }
  if (Object.keys(updates).length === 0) {
    return;
  }
  writeFileSync(envPath, upsertEnv(existing, updates), "utf8");
}

export function writeOperatorEnv(
  root: string,
  updates: Record<string, string>,
): void {
  const envPath = resolve(root, CONFIG_FILE);
  if (!existsSync(envPath)) {
    throw new DomainError(
      "cli.missing_env_file",
      "Run local first-run before saving Hetzner keys.",
    );
  }
  const next = upsertEnv(readFileSync(envPath, "utf8"), updates);
  writeFileSync(envPath, next, "utf8");
}
