import type { LiveTable } from "#application";

const HEADER = `// Generated by \`baseplate types\`. Regenerate after a schema change.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
`;

/**
 * Types come from the live database, so they describe what is actually there
 * rather than what some file claims. Column types are read from Postgres.
 */
export function renderTypes(tables: readonly LiveTable[]): string {
  if (tables.length === 0) {
    return `${HEADER}\nexport type Database = Record<string, never>;\n`;
  }
  const blocks = tables.map((table) => {
    const name = pascal(table.name);
    const row = table.columns
      .map((column) => `  ${column.name}: ${tsType(column.type)}${column.nullable ? " | null" : ""};`)
      .join("\n");
    const insert = table.columns
      .filter((column) => !column.primaryKey && column.name !== table.ownerColumn)
      .map((column) => `  ${column.name}${column.nullable ? "?" : ""}: ${tsType(column.type)}${column.nullable ? " | null" : ""};`)
      .join("\n");
    const update = table.columns
      .filter((column) => !column.primaryKey && column.name !== table.ownerColumn)
      .map((column) => `  ${column.name}?: ${tsType(column.type)}${column.nullable ? " | null" : ""};`)
      .join("\n");
    return `export type ${name}Row = {\n${row}\n};\n\nexport type ${name}Insert = {\n${insert}\n};\n\nexport type ${name}Update = {\n${update}\n};`;
  });
  const database = tables
    .map((table) => {
      const name = pascal(table.name);
      return `  ${table.name}: {\n    Row: ${name}Row;\n    Insert: ${name}Insert;\n    Update: ${name}Update;\n  };`;
    })
    .join("\n");
  return `${HEADER}\n${blocks.join("\n\n")}\n\nexport type Database = {\n${database}\n};\n`;
}

export function tsType(postgresType: string): string {
  if (["boolean"].includes(postgresType)) {
    return "boolean";
  }
  if (
    ["integer", "bigint", "smallint", "numeric", "real", "double precision"].includes(
      postgresType,
    )
  ) {
    return "number";
  }
  if (["json", "jsonb"].includes(postgresType)) {
    return "Json";
  }
  return "string";
}

function pascal(name: string): string {
  return name
    .split(/[_-]/)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join("");
}
